# Generated by Django 3.1.6 on 2021-02-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('H', 'headphone'), ('TW', 'Top wear'), ('BW', 'Bottom Wear')], max_length=2),
        ),
    ]
